#!/bin/bash

# setup.sh - Prepares the environment for the Grammar Fixer

# 1. Get the absolute path of the current directory
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"

# 2. Check for Python
if ! command -v python3 &> /dev/null; then
    echo "Error: python3 could not be found. Please install Python 3."
    exit 1
fi

# 3. Install Dependencies
echo "Installing dependencies..."
pip3 install -r "$PROJECT_DIR/requirements.txt"

# 4. Create .gemini_key if it doesn't exist
KEY_FILE="$PROJECT_DIR/.gemini_key"
if [ ! -f "$KEY_FILE" ]; then
    echo "Creating .gemini_key placeholder..."
    echo "PASTE_YOUR_API_KEY_HERE" > "$KEY_FILE"
    echo "⚠️  Please open '$KEY_FILE' and paste your Gemini API key inside it!"
fi

# 5. Generate the runtime script (run_fixer.sh)
# We generate this script with ABSOLUTE PATHS so it works in Automator/Shortcuts
RUNTIME_SCRIPT="$PROJECT_DIR/run_fixer.sh"
PYTHON_PATH=$(which python3)

echo "Generating run_fixer.sh with absolute paths..."

cat <<EOF > "$RUNTIME_SCRIPT"
#!/bin/bash

# Auto-generated script by setup.sh
# Do not edit this file directly; it is git-ignored.

# 1. Load API Key
KEY_FILE="$PROJECT_DIR/.gemini_key"
if [ -f "\$KEY_FILE" ]; then
    export GEMINI_API_KEY=\$(cat "\$KEY_FILE" | tr -d '\n')
else
    echo "Error: .gemini_key file not found at \$KEY_FILE"
    exit 1
fi

# 2. Run Python Script
# We use the absolute path to python and the script to ensure it runs from anywhere (like Automator)
"$PYTHON_PATH" "$PROJECT_DIR/grammar_fixer.py" "\$@"
EOF

chmod +x "$RUNTIME_SCRIPT"

echo "✅ Setup complete!"
echo "-------------------------------------------------------"
echo "1. Make sure you added your API key to: .gemini_key"
echo "2. In Automator, point your 'Run Shell Script' to:"
echo "   $RUNTIME_SCRIPT"
echo "-------------------------------------------------------"
